(function(){
  const KEY='sipakatau.requirements.single-page.demo.v1';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
  const cell=v=>String(v??'').replace(/\r?\n/g,' ');
  function data(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}}
  function rows(s){return [['SIPAKATAU - FORM KEBUTUHAN DINAS'],['Status','DEMO SINTETIS'],['Nomor referensi',s.submittedId||'DRAFT'],[],['DATA PENGISI','Nilai'],['Nama',s.submitter.name],['Jabatan',s.submitter.position],['Unit',s.submitter.unit],['WhatsApp',s.submitter.phone],['Email',s.submitter.email],[],['WHATSAPP RESMI','Nilai'],['Nomor',s.officialWa],['Nama layanan',s.officialWaName],['Unit pemilik',s.officialWaUnit],['Jam layanan',s.serviceHours],[],['PIMPINAN','Nama','Jabatan','WhatsApp','Email'],...s.leaders.map(x=>['',x.name,x.position,x.phone,x.email]),[],['ADMIN UMUM','Nama','Jabatan','WhatsApp','Email'],...s.generalAdmins.map(x=>['',x.name,x.position,x.phone,x.email]),[],['17 LAYANAN','Nama layanan','Keputusan','Nama','Usulan nama baru','Admin','Jabatan','WhatsApp','Email','Catatan'],...s.services.map(x=>[x.code,x.name,x.decision,x.nameStatus,x.proposedName,x.admin.name,x.admin.position,x.admin.phone,x.admin.email,x.notes]),[],['TAMBAHAN/PENYESUAIAN','Isi'],['Yang ingin ditambahkan',s.additions],['Yang ingin diubah',s.adjustments],['Catatan lain',s.otherNotes]]}
  function crc32(buf){let t=crc32.table||(crc32.table=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0}));let c=0xffffffff;for(const b of buf)c=t[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
  function u16(n){return new Uint8Array([n&255,n>>>8&255])}function u32(n){return new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255])}
  function join(...xs){let n=xs.reduce((a,x)=>a+x.length,0),o=new Uint8Array(n),p=0;xs.forEach(x=>{o.set(x,p);p+=x.length});return o}
  function zip(files){let parts=[],central=[],offset=0;for(const [name,text] of files){let nb=new TextEncoder().encode(name),db=new TextEncoder().encode(text),crc=crc32(db),local=join(u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(db.length),u32(db.length),u16(nb.length),u16(0),nb,db);parts.push(local);central.push(join(u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(db.length),u32(db.length),u16(nb.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nb));offset+=local.length}let c=join(...central),body=join(...parts,c),end=join(u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(c.length),u32(offset),u16(0));return join(body,end)}
  function xlsx(){let s=data();if(!s)return;let r=rows(s),sheet='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+r.map((row,i)=>`<row r="${i+1}">${row.map((v,j)=>`<c r="${String.fromCharCode(65+j)}${i+1}" t="inlineStr"><is><t>${esc(cell(v))}</t></is></c>`).join('')}</row>`).join('')+'</sheetData></worksheet>';let files=[['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Kebutuhan Dinas" sheetId="1" r:id="rId1"/></sheets></workbook>'],['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],['xl/worksheets/sheet1.xml',sheet]];let blob=new Blob([zip(files)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SIPAKATAU_form-kebutuhan-dinas.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function mark(){document.querySelectorAll('[data-req-export="excel"]').forEach(b=>b.dataset.reqExport='xlsx')}
  document.addEventListener('click',e=>{let b=e.target.closest('[data-req-export="xlsx"]');if(b){e.stopImmediatePropagation();xlsx()}});
  window.addEventListener('hashchange',()=>setTimeout(mark,20));setTimeout(mark,20);
})();
